apiVersion: v1
kind: ConfigMap
metadata:
  name: recipes-init-sql
  namespace: my-app
data:
  init.sql: |
    CREATE TABLE recipes (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        instructions TEXT,
        created_at TIMESTAMP DEFAULT NOW()
    );
    
    CREATE TABLE ingredients (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL UNIQUE
    );
    
    CREATE TABLE recipe_ingredients (
        recipe_id INT REFERENCES recipes(id) ON DELETE CASCADE,
        ingredient_id INT REFERENCES ingredients(id) ON DELETE CASCADE,
        quantity VARCHAR(50),
        PRIMARY KEY (recipe_id, ingredient_id)
    );
    
    ALTER TABLE recipes ADD COLUMN IF NOT EXISTS category VARCHAR(50);
    
    INSERT INTO recipes (title, instructions, category) VALUES
    ('Сарма', 'Листови од кисела зелка се полнат со мешавина од мелено месо, ориз и зачини. Се варат во доматен сос.', 'Главно јадење'),
    ('Македонска салата', 'Исечкај домати, краставици, пиперки и кромид. Додај маслиново масло, сол и оригано. Измешај и послужи.', 'Салати'),
    ('Палачинки', 'Измешај јајца, млеко, брашно. Печи на тава.', 'Десерти');
    
    INSERT INTO ingredients (name) VALUES
    ('кисела зелка'),
    ('мелено месо'),
    ('ориз'),
    ('домати'),
    ('кромид'),
    ('маслиново масло'),
    ('сол'),
    ('бибер'),
    ('краставици'),
    ('пиперки'),
    ('јајца'),
    ('млеко'),
    ('брашно'),
    ('оригано');
    
    INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity) VALUES
    -- Сарма
    (1, 1, '12 листови'),
    (1, 2, '300g'),
    (1, 3, '100g'),
    (1, 4, '2'),
    (1, 5, '1'),
    (1, 6, '50ml'),
    (1, 7, 'по вкус'),
    (1, 8, 'по вкус'),
    -- Македонска салата
    (2, 4, '2'),
    (2, 9, '1'),
    (2, 10, '1'),
    (2, 5, '1'),
    (2, 6, '20ml'),
    (2, 7, 'по вкус'),
    (2, 14, 'по вкус'),
    -- Палачинки
    (3, 11, '2'),
    (3, 12, '200ml'),
    (3, 13, '100g');